### ISSUE TITLE
如何加速SAM推理？

### ISSUE THREAD

**Issue by ZHIZIHUABU** [zhujiajian98/sam-hq-tensorrt#1]
您好，十分感谢您你的工作，请问你那边能提供下转化为trt后的推理性能吗？我对sam模型在自己的场景下进行迁移训练，但是性能比较好的是vit_l级模型，我的显卡是rtx 1660s，模型在我的显卡上推理时间为4s，无法用于实时检测，请问你有对sam进行加速推理的需求吗？

**Comment by zhujiajian98** [comment]
按理说您可以通过这个项目转化sam-hq至trt来进行推理的，这样可以大大地减少推理占用显存及加快推理速度，我这边测试的主要是vit-s的推理性能，测试能看到显存占用在1500Mib左右，速度会提速大约3-4倍，您可以尝试一下转化trt

**Comment by zhujiajian98** [comment]
如果没其他问题，我先暂时关闭这个issue哈，后续如果有任何问题都可以重新打开issue或者新建一个。
